name: Deploy Workflow

on:
  push:
    branches:
      - main
      
jobs:
  test_starting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into Staging Server and Test
        id: ssh_staging
        uses: invi5H/ssh-action@v1   
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}

      - name: Run Tests on Known Hosts 
        run: ssh ${{ steps.ssh_staging.outputs.SERVER }} bash /app/deploy.sh risa_kikuchi

  deploy_production:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Production Server and Deploy
        id: ssh_production
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST2 }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT2 }}
          SSH_USER: ${{ secrets.DEV_SSH_USER2 }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY2 }}

      - name: Run Deployment on Production
        run: ssh ${{ steps.ssh_production.outputs.SERVER }} bash /app/deploy.sh risa_kikuchi
